### ISSUE TITLE
GUI not showing COM ports

### ISSUE THREAD

**Issue by Vinay-Gajjar** [hajakuja/control-edx#1]
Hey @hajakuja , Just wondering I was on windows 10 and was not able to fix the com port on the GUI being blank at all times, were you able to fix that. If so how and what are your software and os specs, just to make sure that is not an issue as well.

Thanks in advance.

**Comment by hajakuja** [comment]
It's been quite a while since I used this code, and even then it was a bit outdated. Unfortunately there seems to be no existing documentation from the creators. Note that I didn't write any of it I simply uploaded it to my github for convenience. The authors of the code are the lecturers of an edx.org MITx course. I remember that when I last used it I got it to work somehow but now I get the same problem that you describe. I tried it both on Windows 10 and Linux, it's the same. The issue is with the version of the python libraries that are used. The req.txt file unfortunately doesn't specify any version so pip simply installs the latest version available. I will try to update the req.txt file with versions of the libraries that I found work well enough, though I can't guarantee that you won't have other problems.
